### ISSUE TITLE
Content-Signature Header Field Definition/Example

### ISSUE THREAD

**Issue by franziskuskiefer** [martinthomson/content-signature#3]
I don't think the definition of the Content-Signature header field works this way. From what I understand it is defined as 

```
Content-Signature = 1#csig_params
csig_params = [ parameter *( ";" parameter ) ]
```

such that parameter is a `attribute=value` pair and `value` is a token or quoted-string (according to rfc2616).
The problem is that urlsafe base64 still contains padding (`=`) which is not allowed in token. Thus we have to use quoted-strings for signature values. Same goes for the Encryption-Key header.

**Comment by martinthomson** [comment]
It is customary to omit padding from the URL-safe base64 variant.  But I agree, we should be clear to state that the padding is omitted.
